alwayssunny/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)

urlpatterns = [
    url(r'^weather/', include(('weather.urls', 'weather'), namespace='weather')),
    url(r'^admin/', admin.site.urls),
]

weather/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.current_weather, name="current"),
    path('forecast', views.forecast_weather, name = "forecast")
]

weather/models.py
from django.db import models

# Create your models here.

weather/views.py
from django.shortcuts import render

from django.http import (
    HttpRequest,
    HttpResponseBadRequest,
    HttpResponseForbidden,
    HttpResponseServerError,
    HttpResponse,
    JsonResponse
)
from .utils import get_my_cities_weather, get_forecast
from .consts import CITIES_INFO, DEFAULT_CITY

# Create your views here.

def current_weather(request):
    cities = request.GET.getlist('city', [DEFAULT_CITY])
    data = get_my_cities_weather(cities)
    return render(request, 'weather/index.html', {"weather": data})


def forecast_weather(request):
    city = request.GET.get('city', [DEFAULT_CITY])
    data = get_forecast(city)
    return render(request, 'weather/forecast.html', {"weather": data})

weather/templates/weather/forecast.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/weather/styles.css' %}">
</head>

<body>
    <div class="container-fluid">
        <div class="jumbotron">
            <h1>Forecast Weather</h1>
            <p>5 Days weather for {{weather.city.name}}.</p>
        </div>
        <div class="row align-items-start">
            {% for list in weather.list %}
            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="card p-4">
                    <div class="d-flex">
                        <h6 class="flex-grow-1">{{weather.city.name}}</h6>
                        <h6>{{list.dt_txt}}</h6>
                    </div>
                    <div class="d-flex flex-column temp mt-5 mb-3">
                        <h1 class="mb-0 font-weight-bold" id="heading">{{list.main.temp}} °C</h1> <span class="small grey">{{list.weather.0.main}}</span>
                    </div>
                    <div class="d-flex">
                        <div class="temp-details flex-grow-1">
                            <p class="my-1"> <img src="https://i.imgur.com/B9kqOzp.png" height="17px"> <span> {{list.wind.speed}} km/h </span> </p>
                            <p class="my-1"> <i class="fa fa-tint mr-2" aria-hidden="true"></i> <span> Feels Like {{list.main.feels_like}} </span> </p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</body>

</html>

weather/templates/weather/index.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/weather/styles.css' %}">
</head>

<body>
    <div class="container-fluid">
        <div class="jumbotron ">
            <h1>Malaysia Weather</h1>
            <p>Get current and forecast weathers for the next five days</p>
        </div>

        <div class="row align-items-start">
            {% for city in weather %}
            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="card p-4">
                    <div class="d-flex">
                        <h6 class="flex-grow-1">{{city.name}}</h6>
                        <!-- <h6>16:08</h6> -->
                    </div>
                    <div class="d-flex flex-column temp mt-5 mb-3">
                        <h1 class="mb-0 font-weight-bold" id="heading">{{city.main.temp}} °C </h1> <span class="small grey">{{city.weather.0.main}}</span>
                    </div>
                    <div class="d-flex">
                        <div class="temp-details flex-grow-1">
                            <p class="my-1"> <img src="https://i.imgur.com/B9kqOzp.png" height="17px"> <span> {{city.wind.speed}} km/h </span> </p>
                            <p class="my-1"> <i class="fa fa-tint mr-2" aria-hidden="true"></i> <span> Feels Like {{city.main.feels_like}} </span> </p>
                            <p><a href="{% url 'weather:forecast'%}?city={{city.key}}" class="link-secondary">5 days forecast ..</a> </p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>
</body>

</html>